Add html  in setting
Vasily-N/RSClone pull request #41
Opened 2022-08-22 19:26 UTC by BurakMikita

Add html in setting and add functional in a filed index.ts of setting game

2022-08-22 21:44 UTC, Vasily-N requested changes

2022-08-22 21:44 UTC, Vasily-N commented on frontend/src/views/settingIsGame/index.ts
> +				uiValue = true
Для реверса можно просто uiValue = !uiValue

2022-08-22 21:44 UTC, Vasily-N commented on frontend/src/views/settingIsGame/index.ts
> +			zoomGame: gameSettings.Zoom
Тебе не нужно ЭТО хранить во внутренней переменной, у тебя для этого же есть this:gameSettings.
Вот оттуда и бери значения, а так же задавай именно их; не нужно никакой другой внутренней переменной для значений.

UI = UserInterface = элементы интерфейса.
Т.е. в ней можно хранить this.getElementById('fps__Limit'), this.getElementById('zoom__game') и т.д, чтобы не искать их постояно в документе.

2022-08-22 21:44 UTC, Vasily-N commented on frontend/src/views/settingIsGame/index.ts
> +		this.fpsLimitNumeric = this.initSetting()
Что, зачем?  :D

2022-08-23 13:36 UTC, Vasily-N commented
Ну и я написал в дискорде о "включи Eslint" отдельно его ошибки помечать не стал.

2022-08-24 13:35 UTC, BurakMikita commented on frontend/src/views/settingIsGame/index.ts
> +		this.fpsLimitNumeric = this.initSetting()
а где лучше повесить, что бы функкция слушателей подписалась ?

2022-08-24 15:12 UTC, Vasily-N commented on frontend/src/views/settingIsGame/index.ts
> +		this.fpsLimitNumeric = this.initSetting()
Я про то, что присвоение идёт от функции, которая не дожна возвращать значение этой переменной.

2022-08-24 16:24 UTC, Vasily-N requested changes

2022-08-24 16:24 UTC, Vasily-N commented on frontend/src/views/settingIsGame/index.ts
> +      this.gameSettings.DrawSurfaces = !this.gameSettings.DrawSurfaces;
В этом и похожем лучше задавать значение из чекбокса, а не реверсить, т.к. интерфейс может не совпадать с "бэком".

2022-08-24 16:24 UTC, Vasily-N commented on frontend/src/views/settingIsGame/index.ts
> +  private checkBox(elem: string, uiValue: boolean): void {
Удаляй, оно тебе уже не нужно.

2022-08-24 16:27 UTC, Vasily-N requested changes

2022-08-24 16:27 UTC, Vasily-N commented on frontend/src/views/settingIsGame/index.ts
> +  init: void;
Что это, зачем это.

2022-08-24 17:01 UTC, BurakMikita commented on frontend/src/views/settingIsGame/index.ts
> +  init: void;
так мы же должы где-то вызывать метод initSetting, чтобы подисать на события

2022-08-24 19:38 UTC, Vasily-N approved these changes

2022-08-24 19:41 UTC, merged